services:
  initiator:
    build: .
    networks:
      lan_initiator:
        ipv4_address: 192.168.0.10
    volumes:
      - .:/work
    cap_add:
      - NET_ADMIN
    command:
      - "initiator" # actor
      - "10.0.0.0/24" # internet_subnet
      - "192.168.0.20" # router_ip
  initiator_router:
    build: router
    networks:
      lan_initiator:
        ipv4_address: 192.168.0.20
      internet:
        ipv4_address: 10.0.0.20
    cap_add:
      - NET_ADMIN
    command:
      - "192.168.0.10" # initiator ip address
  relay:
    build: .
    networks:
      internet:
        ipv4_address: 10.0.0.30
    command:
      - "relay" # actor
    volumes:
      - .:/work
  target_router:
    build: router
    networks:
      lan_target:
        ipv4_address: 172.16.0.40
      internet:
        ipv4_address: 10.0.0.40
    cap_add:
      - NET_ADMIN
    command:
      - "172.16.0.50" # target ip address
  target:
    build: .
    networks:
      lan_target:
        ipv4_address: 172.16.0.50
    command:
      - "target" # actor
      - "10.0.0.0/24" # internet_subnet
      - "172.16.0.40" # router_ip
    volumes:
      - .:/work
    cap_add:
      - NET_ADMIN

networks:
  lan_initiator:
    ipam:
      config:
        - subnet: 192.168.0.0/24
  lan_target:
    ipam:
      config:
        - subnet: 172.16.0.0/24
  internet:
    ipam:
      config:
        - subnet: 10.0.0.0/24
